### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by hulleyrob** [mhadam/clutch#1]
Hi im having trouble with stopping and starting items I find in the queue can you give me an example?

Thanks

**Comment by mhadam** [comment]
For sure!
As a word of advice: use a Jupyter notebook if you're trying to figure out clutch. It helps to be able to try out commands in separate blocks and see the results inline.
Here's some code that you should be able to run to stop and start torrents:
```python
from clutch.core import Client
client = Client()
client.list()
client.torrent.get(fields=['id', 'name', 'hashString'])
client.torrent.stop(23)
client.torrent.start(23)
client.torrent.stop([21, 22, 23])
```

21, 22, and 23 are `id` numbers that I found after running `client.list()`.
You can also start or stop torrents based on their `hashString`.
A `hashString` can be mixed into a list of `ids`.

Let me know if anything isn't clear or you need any other help!

**Comment by hulleyrob** [comment]
No thats fine I didnt realise it was just the ID and was trying to send the stop command in the parameters.

None of the links to the sections themselves work by the way, for example:
https://github.com/mhadam/clutch/blob/master/clutch.py#L683 (Client)
https://github.com/mhadam/clutch/blob/master/clutch.py#L342 (Client.Queue)
https://github.com/mhadam/clutch/blob/master/clutch.py#L349 (Client.Session)
https://github.com/mhadam/clutch/blob/master/clutch.py#L417 (Client.Torrent)

Thanks will try again.
