### ISSUE TITLE
Import Literal from typing-extensions

### ISSUE THREAD

**Issue by dmitry-fedoseev** [mhadam/clutch#22]
While trying to run version 4.1 with python3.7 I've got an exception:

```
File "<path removed>/lib/python3.7/site-packages/clutch/schema/user/method/session/accessor.py", line 1, in <module>
    from typing import Literal
ImportError: cannot import name 'Literal' from 'typing' (/usr/lib/python3.7/typing.py)
```

typing.Literal is [new in python3.8](https://docs.python.org/3/library/typing.html#typing.Literal). Please update python dependencies in pyproject.toml.

**Comment by mhadam** [comment]
Thanks for pointing this out! It's backwards compatible in 3.7 but I imported it from the wrong place. Will release a new version with the fix shortly.

**Comment by mhadam** [comment]
@dmitry-fedoseev hoping that fixed your issue! If anything’s still wrong let me know.
