### ISSUE TITLE
Can't call in 3.7?

### ISSUE THREAD

**Issue by thekiefs** [mhadam/clutch#24]
I installed this with pip on 3.7, however it's not loading:   

```
File "/Users/Downloads/plextestproj/tr-complete.py", line 10, in <module>
    from clutch import Client
ImportError: No module named clutch
```

In reading through some comments it seems this module requires 3.8, but I thought pip would recognize that dependency and not install it? Do I need to upgrade python3 in order to use clutch?

**Comment by mhadam** [comment]
Are you sure you installed the package?

From wherever you're calling the script run: `pip list | grep transmission-clutch`

It should return: `transmission-clutch 4.2.0`

If you don't see anything, you're missing the package (install it with `pip install transmission-clutch`).

**Comment by thekiefs** [comment]
Oops, environment problems 🙅 

This fixed it: https://opensource.com/article/19/5/python-3-default-mac

Thanks!
