### ISSUE TITLE
Not really docker friendly

### ISSUE THREAD

**Issue by wagaman** [mhadam/clutch#3]
File "/usr/local/lib/python3.7/site-packages/clutch/core.py", line 757, in invoke
    response = self.connection.post(self.endpoint, json=data, **additional)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for '//None:9091/transmission'

**Comment by wagaman** [comment]
In my case, "transmission" is my address

**Comment by mhadam** [comment]
Hi @wagaman, sorry I didn't see this sooner. I think `requests` requires that you specify a protocol, e.g. `http://transmission`

Let me know if that's the issue, otherwise I'll see if I can figure out a fix.

**Comment by wagaman** [comment]
Hi @mhadam, thank you for following up. I bypassed the potential problem by setting up a shared network for Docker so that I have an IP address for requests to communicate with. But if you could fix it from your side that would be great.  Thanks

**Comment by mhadam** [comment]
@wagaman I'm working on an overhaul of the codebase - and through testing found that what you're doing should have worked.  Did you just set the keyword host="transmission"? Address would be left empty if you port is the default (9091).

**Comment by mhadam** [comment]
Since I think this is solved and it's been opened for a while, I'm going to close. Hopefully the advice above helps but please feel free to open another if you have any issue.
