### ISSUE TITLE
is_finished does not update

### ISSUE THREAD

**Issue by nineclicks** [mhadam/clutch#35]
`json.loads(transmission.torrent.accessor(all_fields=True).json())['arguments']['torrents']`

I am using this line to just get a list of my torrents over a period of time. I am finding that is_finished doesn't update until I reconnect. Also torrents that are removed manually from transmission are not removed from this list until I reconnect.

**Comment by mhadam** [comment]
Are you saying that when you call that line repeatedly, you get the same result? I'll play around with this soon to see if I can reproduce it.

**Comment by nineclicks** [comment]
Progress, status and peers updates, but is_finished does not. Those are three only attributes I am using.

**Comment by nineclicks** [comment]
Sorry, this issue was unrelated to clutch.

**Comment by mhadam** [comment]
Ah ok, thanks for the confirmation! I suspected that might be the case.
